const $ = id => document.getElementById(id);
const DEFAULTS = { polygon:[[-1.2,-.8],[.2,-1.1],[1.1,-.4],[.9,.8],[-.1,.2],[-1,.5]], pathPoints:[[-2.2,-3],[-1.5,-1.1],[1.3,1.1],[.3,3]], pathSmooth:true, mode:'straight', segments:64, samples:32, length:6, startScale:1, endScale:.7, twist:180, radius:3, turns:1, modulation:'linear', amplitude:0, frequency:1, collisionMode:'preserve', clearance:.08, capStart:true, capEnd:true, smooth:true, resample:false, opacity:1, bbox:false, vertices:false };
let state = loadLocal(), activeStation = 0, selected = null, dragging = false, pointer = null, pathSelected = null, pathDragging = false, history = [], historyIndex = -1;
let surface = null, ringLines = null, pathLine = null, vertexPoints = null, boxHelper = null, edgeOverlay = null, boundaryOverlay = null, collisionOverlay = null;
let manifoldApi = null, manifoldPromise = null, manifoldError = '', booleanTimer = null;
const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(40, 1, .01, 1000);
const renderer = new THREE.WebGLRenderer({antialias:true, alpha:true});
const viewport = $('viewport');
renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setClearColor(0x000000, 0); viewport.replaceChildren(renderer.domElement);
camera.position.set(8, 6, 10);
const controls = new THREE.OrbitControls(camera, renderer.domElement); controls.enableDamping = true;
scene.add(new THREE.HemisphereLight(0xbec8e0, 0x101218, 2.1));
const keyLight = new THREE.DirectionalLight(0xffddc5, 2.3); keyLight.position.set(5,7,9); scene.add(keyLight);
const grid = new THREE.GridHelper(24, 24, 0x43506a, 0x27303e); scene.add(grid);
const axes = new THREE.AxesHelper(2); scene.add(axes);

function clone(v){ return JSON.parse(JSON.stringify(v)); }
function loadLocal(){ try { return {...clone(DEFAULTS), ...JSON.parse(localStorage.getItem('irregular-polygon-sweep-v1'))}; } catch { return clone(DEFAULTS); } }
function station(polygon, position, scale){return {polygon:clone(polygon),position,scale,rotation:0,offsetX:0,offsetY:0};}
function ensureStations(){const source=state.polygon?.length?state.polygon:DEFAULTS.polygon;if(!Array.isArray(state.stations)||state.stations.length<2)state.stations=[station(source,0,.04),station(source,.5,1),station(source,1,.04)];if(!Array.isArray(state.pathPoints)||state.pathPoints.length<2)state.pathPoints=clone(DEFAULTS.pathPoints);state.pathSmooth=state.pathSmooth!==false;state.collisionMode??='preserve';state.clearance=Number(state.clearance??.08);state.stations.forEach(s=>{s.polygon??=clone(source);s.position=THREE.MathUtils.clamp(Number(s.position??.5),0,1);s.scale=Number(s.scale??1);s.rotation=Number(s.rotation??0);s.offsetX=Number(s.offsetX??0);s.offsetY=Number(s.offsetY??0);});state.stations.sort((a,b)=>a.position-b.position);activeStation=Math.min(activeStation,state.stations.length-1);state.polygon=state.stations[activeStation].polygon;}
ensureStations();
function persist(){ localStorage.setItem('irregular-polygon-sweep-v1', JSON.stringify(state)); }
function checkpoint(){ const next=clone(state); history=history.slice(0,historyIndex+1); history.push(next); historyIndex=history.length-1; if(history.length>80){history.shift(); historyIndex--;} updateUndoButtons(); }
function restore(snapshot){ state=clone(snapshot); ensureStations(); populateControls(); rebuild(); }
function updateUndoButtons(){ $('undoBtn').disabled=historyIndex<1; $('redoBtn').disabled=historyIndex>=history.length-1; }

function signedArea(points=state.polygon){ return points.reduce((sum,p,i)=>sum+p[0]*points[(i+1)%points.length][1]-p[1]*points[(i+1)%points.length][0],0)/2; }
function polygonCentroid(points=state.polygon){ const a=signedArea(points); if(Math.abs(a)<1e-8)return [0,0]; let x=0,y=0; points.forEach((p,i)=>{const q=points[(i+1)%points.length], cross=p[0]*q[1]-q[0]*p[1]; x+=(p[0]+q[0])*cross;y+=(p[1]+q[1])*cross;}); return [x/(6*a),y/(6*a)]; }
function polygonPerimeter(points=state.polygon){ return points.reduce((sum,p,i)=>sum+Math.hypot(p[0]-points[(i+1)%points.length][0],p[1]-points[(i+1)%points.length][1]),0); }
function orient(a,b,c){ return (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]); }
function segmentsIntersect(a,b,c,d){ const ab1=orient(a,b,c),ab2=orient(a,b,d),cd1=orient(c,d,a),cd2=orient(c,d,b); return ab1*ab2<0&&cd1*cd2<0; }
function validation(points=state.polygon){ const p=points; if(p.length<3)return 'Need at least three vertices.'; if(Math.abs(signedArea(p))<.0001)return 'Polygon area is too small.'; for(let i=0;i<p.length;i++){const q=p[(i+1)%p.length];if(Math.hypot(p[0]-q[0],p[1]-q[1])<.001)return 'Polygon has a zero-length edge.';for(let j=i+1;j<p.length;j++){if(Math.abs(i-j)<2||(i===0&&j===p.length-1))continue;if(segmentsIntersect(p[i],q,p[j],p[(j+1)%p.length]))return 'Polygon self-intersects.';}} return ''; }
function resampleBoundary(points,count){ const lens=[], total=polygonPerimeter(points); let cumulative=0; points.forEach((p,i)=>{const q=points[(i+1)%points.length];cumulative+=Math.hypot(q[0]-p[0],q[1]-p[1]);lens.push(cumulative);}); return Array.from({length:count},(_,i)=>{const d=i*total/count, edge=lens.findIndex(v=>v>=d), before=edge?lens[edge-1]:0, a=points[edge], b=points[(edge+1)%points.length], t=(d-before)/(lens[edge]-before);return [a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t];}); }

function editorToWorld([x,y]){ return [(x-160)/95,(160-y)/95]; }
function editorPoint(e){const r=$('polygonEditor').getBoundingClientRect(); return [(e.clientX-r.left)*320/r.width,(e.clientY-r.top)*320/r.height];}
function snap(p){ return $('snapToggle').checked?p.map(v=>Math.round(v/.2)*.2):p; }
function renderEditor(){
  const svg=$('polygonEditor'), p=state.polygon, to=([x,y])=>[160+x*95,160-y*95]; let html='';
  if($('gridToggle').checked) for(let i=20;i<320;i+=20) html+=`<path class="editor-grid" d="M${i} 0V320M0 ${i}H320"/>`;
  html+='<path class="editor-axis" d="M160 0V320M0 160H320"/>';
  if(p.length){ const screen=p.map(to); html+=`<polygon class="polygon-fill" style="fill-opacity:${$('fillToggle').checked?.13:0}" points="${screen.map(v=>v.join(',')).join(' ')}"/>`;
    if(dragging&&pointer&&screen.length)html+=`<line class="preview-line" x1="${screen.at(-1)[0]}" y1="${screen.at(-1)[1]}" x2="${pointer[0]}" y2="${pointer[1]}"/>`;
    const c=to(polygonCentroid()); html+=`<circle class="centroid" cx="${c[0]}" cy="${c[1]}" r="3"/>`;
    screen.forEach((v,i)=>{html+=`<circle class="vertex ${selected===i?'selected':''}" data-index="${i}" cx="${v[0]}" cy="${v[1]}" r="5"/>`;if($('indicesToggle').checked)html+=`<text class="vertex-index" x="${v[0]+8}" y="${v[1]-7}">${i}</text>`;});
  }
  svg.innerHTML=html; const error=validation(); $('statusPill').textContent=error||'Valid polygon'; $('statusPill').style.color=error?'var(--exo)':'var(--green)';
  $('polygonStats').textContent=`${p.length} vertices · ${Math.abs(signedArea()).toFixed(2)} area · ${polygonPerimeter().toFixed(2)} perimeter · ${signedArea()>=0?'CCW':'CW'}`;
}
function renderStations(){ensureStations();const list=$('stationList');list.innerHTML='';state.stations.forEach((s,i)=>{const b=document.createElement('button');b.className=`station-item ${i===activeStation?'active':''}`;b.innerHTML=`<span class="station-dot"></span><span>Section ${i+1}</span><small>${Math.round(s.position*100)}% · ×${s.scale.toFixed(2)}</small>`;b.onclick=()=>{activeStation=i;state.polygon=state.stations[i].polygon;populateControls();rebuild();};list.append(b);});const s=state.stations[activeStation];$('stationName').textContent=`Section ${activeStation+1} — structural cross-section`; $('stationPositionInput').value=s.position;$('stationScaleInput').value=s.scale;$('stationRotationInput').value=s.rotation;$('stationOffsetXInput').value=s.offsetX;$('stationOffsetYInput').value=s.offsetY;$('removeStationBtn').disabled=state.stations.length<=2;}
function beginEdit(){}
const editor=$('polygonEditor');
editor.addEventListener('pointerdown',e=>{const id=e.target.dataset.index;if(id!==undefined){beginEdit();selected=+id;dragging=true;editor.setPointerCapture(e.pointerId);renderEditor();return;} beginEdit(); state.polygon.push(snap(editorToWorld(editorPoint(e)))); selected=state.polygon.length-1; dragging=true; rebuild();});
editor.addEventListener('pointermove',e=>{pointer=editorPoint(e); if(dragging&&selected!==null){state.polygon[selected]=snap(editorToWorld(pointer)); rebuild(true);}else renderEditor();});
editor.addEventListener('pointerup',()=>{dragging=false;selected=null;checkpoint();persist();renderEditor();});
editor.addEventListener('dblclick',e=>{e.preventDefault(); if(state.polygon.length<2)return;beginEdit();const q=snap(editorToWorld(editorPoint(e))),p=state.polygon;let best=Infinity,insert=0;p.forEach((a,i)=>{const b=p[(i+1)%p.length],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((q[0]-a[0])*dx+(q[1]-a[1])*dy)/(dx*dx+dy*dy))),d=Math.hypot(q[0]-(a[0]+dx*t),q[1]-(a[1]+dy*t));if(d<best){best=d;insert=i+1;}});p.splice(insert,0,q);checkpoint();rebuild();persist();});

function pathEditorPoint(event){const r=$('pathEditor').getBoundingClientRect();return[(event.clientX-r.left)*320/r.width,(event.clientY-r.top)*320/r.height];}
function pathToWorld([x,y]){return[(x-160)/44,(160-y)/44];}
function renderPathEditor(){const svg=$('pathEditor'),points=state.pathPoints,to=([x,z])=>[160+x*44,160-z*44];let html='';for(let i=20;i<320;i+=20)html+=`<path class="editor-grid" d="M${i} 0V320M0 ${i}H320"/>`;html+='<path class="editor-axis" d="M160 0V320M0 160H320"/><text class="vertex-index" x="300" y="154">X</text><text class="vertex-index" x="166" y="15">Z</text>';const screen=points.map(to);if(screen.length>1)html+=`<polyline class="path-sketch" points="${screen.map(p=>p.join(',')).join(' ')}"/>`;if(state.pathSmooth&&screen.length>2){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(p[0],0,p[1])),false,'centripetal');const smooth=curve.getPoints(80).map(p=>to([p.x,p.z]).join(',')).join(' ');html+=`<polyline class="path-smooth" points="${smooth}"/>`;}screen.forEach((p,i)=>html+=`<circle class="vertex ${pathSelected===i?'selected':''}" data-path-index="${i}" cx="${p[0]}" cy="${p[1]}" r="5"/>`);svg.innerHTML=html;}
const pathEditor=$('pathEditor');
pathEditor.addEventListener('pointerdown',event=>{if(state.mode!=='drawn'){state.mode='drawn';$('modeInput').value='drawn';}const id=event.target.dataset.pathIndex;if(id!==undefined){pathSelected=+id;pathDragging=true;pathEditor.setPointerCapture(event.pointerId);renderPathEditor();return;}state.pathPoints.push(pathToWorld(pathEditorPoint(event)));pathSelected=state.pathPoints.length-1;pathDragging=true;rebuild();});
pathEditor.addEventListener('pointermove',event=>{if(pathDragging&&pathSelected!==null){state.pathPoints[pathSelected]=pathToWorld(pathEditorPoint(event));rebuild(true);}});
pathEditor.addEventListener('pointerup',()=>{pathDragging=false;checkpoint();rebuild();});
pathEditor.addEventListener('dblclick',event=>{event.preventDefault();if(state.pathPoints.length<2)return;const q=pathToWorld(pathEditorPoint(event)),p=state.pathPoints;let best=Infinity,insert=0;p.forEach((a,i)=>{if(i===p.length-1)return;const b=p[i+1],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((q[0]-a[0])*dx+(q[1]-a[1])*dy)/(dx*dx+dy*dy))),d=Math.hypot(q[0]-(a[0]+dx*t),q[1]-(a[1]+dy*t));if(d<best){best=d;insert=i+1;}});p.splice(insert,0,q);checkpoint();rebuild();});

function pointAlongPolyline(points,t){const lengths=[],total=points.reduce((sum,p,i)=>{if(!i)return 0;const length=p.distanceTo(points[i-1]);lengths.push((lengths.at(-1)||0)+length);return sum+length;},0),target=t*total;let index=lengths.findIndex(length=>length>=target);if(index<0)index=lengths.length-1;const before=index?lengths[index-1]:0,part=(target-before)/Math.max(.00001,lengths[index]-before);return points[index].clone().lerp(points[index+1],part);}
function pathAt(t){ const {mode,length,radius,turns}=state; if(mode==='arc'){const a=Math.PI*turns*t;return new THREE.Vector3(radius*Math.sin(a),0,radius*(1-Math.cos(a)));} if(mode==='helix'||mode==='ring'){const a=Math.PI*2*turns*t;return new THREE.Vector3(radius*Math.cos(a),radius*Math.sin(a),mode==='ring'?0:length*t);} if(mode==='bezier'){const inv=1-t,p0=new THREE.Vector3(0,0,0),p1=new THREE.Vector3(-radius, radius*.65, length*.25),p2=new THREE.Vector3(radius,-radius*.4,length*.68),p3=new THREE.Vector3(0,0,length);return p0.multiplyScalar(inv**3).add(p1.multiplyScalar(3*inv*inv*t)).add(p2.multiplyScalar(3*inv*t*t)).add(p3.multiplyScalar(t**3));} if(mode==='drawn'){const points=state.pathPoints.map(p=>new THREE.Vector3(p[0],0,p[1]));return state.pathSmooth&&points.length>2?new THREE.CatmullRomCurve3(points,false,'centripetal').getPointAt(t):pointAlongPolyline(points,t);} return new THREE.Vector3(0,0,length*t); }
function makeFrames(points,closed){
  const tangents=points.map((p,i)=>{const prev=points[closed?(i-1+points.length)%points.length:Math.max(0,i-1)],next=points[closed?(i+1)%points.length:Math.min(points.length-1,i+1)];return next.clone().sub(prev).normalize();});
  let normal=new THREE.Vector3(0,1,0); if(Math.abs(normal.dot(tangents[0]))>.9)normal.set(1,0,0); normal.addScaledVector(tangents[0],-normal.dot(tangents[0])).normalize();
  const frames=[]; tangents.forEach((t,i)=>{if(i){const axis=tangents[i-1].clone().cross(t),len=axis.length();if(len>1e-7)normal.applyAxisAngle(axis.normalize(),Math.atan2(len,tangents[i-1].dot(t)));}const binormal=t.clone().cross(normal).normalize();normal=binormal.clone().cross(t).normalize();frames.push({normal:normal.clone(),binormal});});
  if(closed){const end=frames.at(-1), start=frames[0], tangent=tangents[0], cross=end.normal.clone().cross(start.normal), residual=Math.atan2(cross.dot(tangent),end.normal.dot(start.normal));frames.forEach((f,i)=>{const correction=-residual*i/frames.length;f.normal.applyAxisAngle(tangents[i],correction);f.binormal.applyAxisAngle(tangents[i],correction);});}
  return frames;
}
function modulatedScale(t){ let base; if(state.modulation==='constant')base=state.startScale; else if(state.modulation==='stepped'){const steps=Math.max(1,Math.round(state.frequency));base=state.startScale+(state.endScale-state.startScale)*Math.floor(t*steps)/steps;} else base=THREE.MathUtils.lerp(state.startScale,state.endScale,t); if(state.modulation==='sine')base*=1+state.amplitude*Math.sin(Math.PI*2*state.frequency*t); if(state.modulation==='pulse')base*=1+state.amplitude*Math.abs(Math.sin(Math.PI*state.frequency*t));return Math.max(.01,base); }
function alignTo(reference, candidate){let best=candidate,bestCost=Infinity;for(let shift=0;shift<candidate.length;shift++){const rotated=candidate.map((_,i)=>candidate[(i+shift)%candidate.length]),cost=rotated.reduce((sum,p,i)=>sum+(p[0]-reference[i][0])**2+(p[1]-reference[i][1])**2,0);if(cost<bestCost){bestCost=cost;best=rotated;}}return best;}
function localBendRadius(points,index,closed){if(!closed&&(index===0||index===points.length-1))return Infinity;const a=points[(index-1+points.length)%points.length],b=points[index],c=points[(index+1)%points.length],ab=a.distanceTo(b),bc=b.distanceTo(c),ac=a.distanceTo(c),twiceArea=b.clone().sub(a).cross(c.clone().sub(a)).length();return twiceArea<1e-6?Infinity:(ab*bc*ac)/(2*twiceArea);}
function construct(){
  ensureStations(); const invalid=state.stations.find(s=>validation(s.polygon)); if(invalid)return {issue:validation(invalid.polygon)};
  const n=Math.max(3,state.samples), stations=state.stations.map(s=>({...s,polygon:resampleBoundary(s.polygon,n)})); for(let i=1;i<stations.length;i++)stations[i].polygon=alignTo(stations[i-1].polygon,stations[i].polygon);
  const closed=state.mode==='ring', ringsCount=closed?Math.max(3,state.segments):Math.max(2,state.segments+1), points=Array.from({length:ringsCount},(_,i)=>pathAt(i/(closed?ringsCount:ringsCount-1))), frames=makeFrames(points,closed), positions=[],indices=[],ringRadii=[],collisionRings=new Set();let tightBends=0;
  for(let r=0;r<ringsCount;r++){const t=r/(closed?ringsCount:ringsCount-1),found=stations.findIndex(s=>s.position>=t),rightIndex=found<0?stations.length-1:Math.min(stations.length-1,Math.max(1,found)),right=stations[rightIndex],left=stations[Math.max(0,rightIndex-1)],span=Math.max(.00001,right.position-left.position),u=THREE.MathUtils.clamp((t-left.position)/span,0,1),f=frames[r],sectionExtent=Math.max(...left.polygon.map(p=>Math.hypot(p[0],p[1])),...right.polygon.map(p=>Math.hypot(p[0],p[1])),.0001),rawScale=THREE.MathUtils.lerp(left.scale,right.scale,u)*modulatedScale(t),bendRadius=localBendRadius(points,r,closed),allowed=bendRadius*(1-state.clearance),isTight=rawScale*sectionExtent>allowed;ringRadii[r]=rawScale*sectionExtent;let scale=rawScale;if(isTight){tightBends++;collisionRings.add(r);if(state.collisionMode==='clearance')scale=Math.min(rawScale,allowed/sectionExtent);}const angle=THREE.MathUtils.degToRad(THREE.MathUtils.lerp(left.rotation,right.rotation,u)+state.twist*t),offsetX=THREE.MathUtils.lerp(left.offsetX,right.offsetX,u),offsetY=THREE.MathUtils.lerp(left.offsetY,right.offsetY,u),c=Math.cos(angle),s=Math.sin(angle);for(let i=0;i<n;i++){const x=THREE.MathUtils.lerp(left.polygon[i][0],right.polygon[i][0],u),y=THREE.MathUtils.lerp(left.polygon[i][1],right.polygon[i][1],u),localN=x*c-y*s+offsetX,localB=x*s+y*c+offsetY,v=points[r].clone().addScaledVector(f.normal,localN*scale).addScaledVector(f.binormal,localB*scale);positions.push(v.x,v.y,v.z);}}
  const pathDistance=[0];for(let r=1;r<ringsCount;r++)pathDistance[r]=pathDistance[r-1]+points[r].distanceTo(points[r-1]);for(let a=0;a<ringsCount;a++)for(let b=a+4;b<ringsCount;b++){const span=ringRadii[a]+ringRadii[b],alongPath=pathDistance[b]-pathDistance[a];if(alongPath>span*1.25&&points[a].distanceTo(points[b])<span*.9){collisionRings.add(a);collisionRings.add(b);}}
  const pairs=closed?ringsCount:ringsCount-1;for(let r=0;r<pairs;r++)for(let i=0;i<n;i++){const a=r*n+i,b=r*n+(i+1)%n,c=((r+1)%ringsCount)*n+(i+1)%n,d=((r+1)%ringsCount)*n+i;indices.push(a,b,d,b,c,d);}
  if(!closed){const startCaps=THREE.ShapeUtils.triangulateShape(stations[0].polygon.map(p=>new THREE.Vector2(...p)),[]),endCaps=THREE.ShapeUtils.triangulateShape(stations.at(-1).polygon.map(p=>new THREE.Vector2(...p)),[]);if(state.capStart)startCaps.forEach(([a,b,c])=>indices.push(c,b,a));if(state.capEnd)endCaps.forEach(([a,b,c])=>indices.push((ringsCount-1)*n+a,(ringsCount-1)*n+b,(ringsCount-1)*n+c));}
  const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometry.setIndex(indices);geometry.computeVertexNormals();return {geometry, points, ringRadii, collisionRings:[...collisionRings], ringsCount, sectionCount:n, triangles:indices.length/3, closed, tightBends};
}
function disposeObject(object){if(!object)return;scene.remove(object);object.geometry?.dispose();if(Array.isArray(object.material))object.material.forEach(m=>m.dispose());else object.material?.dispose();}
function boundaryGeometry(geometry){const position=geometry.getAttribute('position'),index=geometry.index?.array||Array.from({length:position.count},(_,i)=>i),edges=new Map(),points=[],vertexKey=i=>`${Math.round(position.getX(i)*1e6)}:${Math.round(position.getY(i)*1e6)}:${Math.round(position.getZ(i)*1e6)}`;for(let i=0;i<index.length;i+=3){const triangle=[index[i],index[i+1],index[i+2]];for(let edge=0;edge<3;edge++){const a=triangle[edge],b=triangle[(edge+1)%3],aKey=vertexKey(a),bKey=vertexKey(b),key=aKey<bKey?`${aKey}|${bKey}`:`${bKey}|${aKey}`,record=edges.get(key)||{count:0,a,b};record.count++;edges.set(key,record);}}for(const record of edges.values())if(record.count===1)points.push(position.getX(record.a),position.getY(record.a),position.getZ(record.a),position.getX(record.b),position.getY(record.b),position.getZ(record.b));const output=new THREE.BufferGeometry();output.setAttribute('position',new THREE.Float32BufferAttribute(points,3));return output;}
function triangleHitsTriangle(a,b,c,d,e,f){const eps=1e-7,normalA=b.clone().sub(a).cross(c.clone().sub(a)),normalB=e.clone().sub(d).cross(f.clone().sub(d));if(normalA.lengthSq()<eps||normalB.lengthSq()<eps)return false;const inside=(p,x,y,z,n)=>{const u=y.clone().sub(x),v=z.clone().sub(x),w=p.clone().sub(x),den=u.dot(u)*v.dot(v)-u.dot(v)**2,s=(w.dot(u)*v.dot(v)-w.dot(v)*u.dot(v))/den,t=(w.dot(v)*u.dot(u)-w.dot(u)*u.dot(v))/den;return Math.abs(n.dot(w))<eps&&s>=-eps&&t>=-eps&&s+t<=1+eps;};const hit=(p,q,n,plane,x,y,z)=>{const direction=q.clone().sub(p),den=n.dot(direction);if(Math.abs(den)<eps)return false;const t=(plane-n.dot(p))/den;return t>=-eps&&t<=1+eps&&inside(p.addScaledVector(direction,t),x,y,z,n);};const planeA=normalA.dot(a),planeB=normalB.dot(d),sa=[d,e,f].map(p=>normalA.dot(p)-planeA),sb=[a,b,c].map(p=>normalB.dot(p)-planeB);if(sa.every(v=>v>eps)||sa.every(v=>v<-eps)||sb.every(v=>v>eps)||sb.every(v=>v<-eps))return false;for(const [p,q]of [[a,b],[b,c],[c,a]])if(hit(p,q,normalB,planeB,d,e,f))return true;for(const [p,q]of [[d,e],[e,f],[f,d]])if(hit(p,q,normalA,planeA,a,b,c))return true;return false;}
function sweptSegmentsHit(geometry,first,second,count){const position=geometry.getAttribute('position'),triangles=segment=>{const out=[];for(let i=0;i<count;i++){const a=segment*count+i,b=segment*count+(i+1)%count,c=(segment+1)*count+(i+1)%count,d=(segment+1)*count+i;out.push([a,b,d],[b,c,d]);}return out;},point=index=>new THREE.Vector3().fromBufferAttribute(position,index);for(const left of triangles(first)){const a=point(left[0]),b=point(left[1]),c=point(left[2]),box=new THREE.Box3().setFromPoints([a,b,c]);for(const right of triangles(second)){const d=point(right[0]),e=point(right[1]),f=point(right[2]);if(box.intersectsBox(new THREE.Box3().setFromPoints([d,e,f]))&&triangleHitsTriangle(a,b,c,d,e,f))return true;}}return false;}
function sweptSegmentTriangleHits(geometry,first,second,count){const position=geometry.getAttribute('position'),triangles=segment=>{const out=[];for(let i=0;i<count;i++){const a=segment*count+i,b=segment*count+(i+1)%count,c=(segment+1)*count+(i+1)%count,d=(segment+1)*count+i;out.push([a,b,d],[b,c,d]);}return out;},point=index=>new THREE.Vector3().fromBufferAttribute(position,index),hits=[];for(const left of triangles(first)){const a=point(left[0]),b=point(left[1]),c=point(left[2]),box=new THREE.Box3().setFromPoints([a,b,c]);for(const right of triangles(second)){const d=point(right[0]),e=point(right[1]),f=point(right[2]);if(box.intersectsBox(new THREE.Box3().setFromPoints([d,e,f]))&&triangleHitsTriangle(a,b,c,d,e,f))hits.push(left,right);}}return hits;}
function ensureManifold(){
  if(manifoldApi)return Promise.resolve(manifoldApi);
  if(manifoldPromise)return manifoldPromise;
  if(!globalThis.ManifoldModule){manifoldError='The Boolean engine did not load.';return Promise.reject(new Error(manifoldError));}
  if(!(globalThis.ManifoldWasmBinary instanceof Uint8Array)){manifoldError='The embedded Boolean runtime did not load. Fully reload this page.';return Promise.reject(new Error(manifoldError));}
  const startup=globalThis.ManifoldModule({wasmBinary:globalThis.ManifoldWasmBinary}).then(api=>{api.setup();manifoldApi=api;return api;}),timeout=new Promise((_,reject)=>setTimeout(()=>reject(new Error('Boolean engine startup timed out. Fully reload this page.')),8000));
  manifoldPromise=Promise.race([startup,timeout]).catch(error=>{manifoldError=error?.message||'The Boolean engine could not start.';manifoldPromise=null;throw error;});
  return manifoldPromise;
}
function ringTriangulation(geometry,ring,count){
  const position=geometry.getAttribute('position'),origin=new THREE.Vector3().fromBufferAttribute(position,ring*count),vertices=Array.from({length:count},(_,i)=>new THREE.Vector3().fromBufferAttribute(position,ring*count+i));
  const normal=new THREE.Vector3();for(let i=0;i<count;i++){const a=vertices[i],b=vertices[(i+1)%count];normal.x+=(a.y-b.y)*(a.z+b.z);normal.y+=(a.z-b.z)*(a.x+b.x);normal.z+=(a.x-b.x)*(a.y+b.y);}if(normal.lengthSq()<1e-12)return [];normal.normalize();
  const u=vertices[1].clone().sub(origin).normalize(),v=normal.clone().cross(u);return THREE.ShapeUtils.triangulateShape(vertices.map(p=>new THREE.Vector2(p.clone().sub(origin).dot(u),p.clone().sub(origin).dot(v))),[]);
}
function createSpanSolid(geometry,segments,ringsCount,count,api){
  const position=geometry.getAttribute('position'),rings=[segments[0],...segments.map(segment=>(segment+1)%ringsCount)],verts=new Float32Array(rings.length*count*3),triangles=[];
  rings.forEach((ring,row)=>{for(let i=0;i<count;i++){const target=(row*count+i)*3;verts[target]=position.getX(ring*count+i);verts[target+1]=position.getY(ring*count+i);verts[target+2]=position.getZ(ring*count+i);}});
  for(let row=0;row<rings.length-1;row++)for(let i=0;i<count;i++){const a=row*count+i,b=row*count+(i+1)%count,c=(row+1)*count+(i+1)%count,d=(row+1)*count+i;triangles.push(a,b,d,b,c,d);}
  const first=ringTriangulation(geometry,rings[0],count),last=ringTriangulation(geometry,rings.at(-1),count);if(!first.length||!last.length)throw new Error('A cross-section could not be capped for Boolean union.');
  first.forEach(([a,b,c])=>triangles.push(c,b,a));const lastOffset=(rings.length-1)*count;last.forEach(([a,b,c])=>triangles.push(lastOffset+a,lastOffset+b,lastOffset+c));
  return api.Manifold.ofMesh(new api.Mesh({numProp:3,vertProperties:verts,triVerts:new Uint32Array(triangles)}));
}
function booleanSpans(result){
  const pairs=result.closed?result.ringsCount:result.ringsCount-1,position=result.geometry.getAttribute('position'),bounds=[];
  const ringRadius=Array.from({length:result.ringsCount},(_,ring)=>{let radius=0;for(let i=0;i<result.sectionCount;i++)radius=Math.max(radius,result.points[ring].distanceTo(new THREE.Vector3().fromBufferAttribute(position,ring*result.sectionCount+i)));return radius;}),segmentDistance=(a,b,c,d)=>{const u=b.clone().sub(a),v=d.clone().sub(c),w=a.clone().sub(c),A=u.dot(u),B=u.dot(v),C=v.dot(v),D=u.dot(w),E=v.dot(w),den=A*C-B*B;let s,t;if(den<1e-10){s=0;t=THREE.MathUtils.clamp(E/C,0,1);}else{s=THREE.MathUtils.clamp((B*E-C*D)/den,0,1);t=THREE.MathUtils.clamp((A*E-B*D)/den,0,1);if(s===0||s===1)t=THREE.MathUtils.clamp((B*s+E)/C,0,1);if(t===0||t===1)s=THREE.MathUtils.clamp((B*t-D)/A,0,1);}return a.clone().addScaledVector(u,s).distanceTo(c.clone().addScaledVector(v,t));};
  for(let segment=0;segment<pairs;segment++){const box=new THREE.Box3(),next=(segment+1)%result.ringsCount;for(const ring of [segment,next])for(let i=0;i<result.sectionCount;i++)box.expandByPoint(new THREE.Vector3().fromBufferAttribute(position,ring*result.sectionCount+i));bounds.push(box);}
  const marked=new Set(),intersectingTriangles=new Map(),adjacent=(a,b)=>Math.abs(a-b)<=1||(result.closed&&Math.abs(a-b)===pairs-1);
  for(let a=0;a<pairs;a++)for(let b=a+1;b<pairs;b++){if(adjacent(a,b)||!bounds[a].intersectsBox(bounds[b]))continue;const hits=sweptSegmentTriangleHits(result.geometry,a,b,result.sectionCount);if(hits.length){marked.add(a);marked.add(b);hits.forEach(triangle=>intersectingTriangles.set(triangle.join(':'),triangle));}}
  if(!marked.size)return {spans:[],hasCandidates:false,intersectingTriangles:[]};
  const spans=[];for(let segment=0;segment<pairs;){if(marked.has(segment)){spans.push([segment++]);continue;}const span=[];while(segment<pairs&&!marked.has(segment))span.push(segment++);spans.push(span);}return {spans,hasCandidates:true,intersectingTriangles:[...intersectingTriangles.values()]};
}
function buildBooleanUnion(result,plan=booleanSpans(result)){
  if(!manifoldApi)return null;
  if(!plan.hasCandidates)return {geometry:result.geometry,merged:false,operands:0};const pairs=result.closed?result.ringsCount:result.ringsCount-1,chunkSize=Math.max(2,Math.ceil(pairs/8)),spans=[];
  for(let start=0;start<pairs;start+=chunkSize){const from=result.closed?(start-1+pairs)%pairs:Math.max(0,start-1),to=result.closed?(Math.min(pairs,start+chunkSize)+1)%pairs:Math.min(pairs-1,start+chunkSize);const span=[];let segment=from;do{span.push(segment);if(segment===to)break;segment=(segment+1)%pairs;}while(span.length<=pairs);spans.push(span);}
  const solids=[],allocations=[];
  try{
    for(const span of spans){const solid=createSpanSolid(result.geometry,span,result.ringsCount,result.sectionCount,manifoldApi);solids.push(solid);allocations.push(solid);}
    let working=solids.slice();while(working.length>1){const next=[];for(let start=0;start<working.length;start+=4){const batch=working.slice(start,start+4),out=batch.length===1?batch[0]:manifoldApi.Manifold.union(batch);if(batch.length>1)allocations.push(out);next.push(out);}working=next;}
    const united=working[0];if(united.status()!=='NoError')throw new Error(`Boolean result is not manifold: ${united.status()}`);const mesh=united.getMesh(),positions=new Float32Array(mesh.vertProperties),indices=new Uint32Array(mesh.triVerts),geometry=new THREE.BufferGeometry();
    geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));geometry.setIndex(new THREE.BufferAttribute(indices,1));geometry.computeVertexNormals();return {geometry,merged:true,operands:solids.length};
  }finally{new Set(allocations).forEach(s=>s.delete());}
}
function rebuild(deferBoolean=false){
  ensureStations();renderEditor();renderPathEditor();renderStations(); const result=construct(); disposeObject(surface);disposeObject(ringLines);disposeObject(pathLine);disposeObject(vertexPoints);disposeObject(boxHelper);disposeObject(edgeOverlay);disposeObject(boundaryOverlay);disposeObject(collisionOverlay);surface=ringLines=pathLine=vertexPoints=boxHelper=edgeOverlay=boundaryOverlay=collisionOverlay=null;
  if(result.issue){$('meshMeta').textContent=`Mesh generation paused — ${result.issue}`;$('meshStats').innerHTML='';return;}
  const collisionDetection=(state.collisionMode==='merge'||$('collisionBtn').classList.contains('active'))?booleanSpans(result):null;let displayGeometry=result.geometry,booleanMerged=false,booleanChecked=false,booleanOperands=0,booleanQueued=false;
  if(state.collisionMode==='merge'){
    if(deferBoolean){clearTimeout(booleanTimer);booleanTimer=setTimeout(()=>rebuild(),180);booleanQueued=true;}
    else if(manifoldApi){try{const booleanResult=buildBooleanUnion(result,collisionDetection);displayGeometry=booleanResult.geometry;booleanMerged=booleanResult.merged;booleanChecked=true;booleanOperands=booleanResult.operands;}catch(error){manifoldError=error?.message||'Boolean union failed.';}}
    else {ensureManifold().then(()=>{if(state.collisionMode==='merge')rebuild();}).catch(()=>{});}
  }
  const material=new THREE.MeshStandardMaterial({color:0xa58ee8,roughness:.42,metalness:.06,side:THREE.DoubleSide,transparent:state.opacity<1,opacity:state.opacity,flatShading:state.collisionMode==='merge'||!state.smooth});surface=new THREE.Mesh(displayGeometry,material);scene.add(surface);
  const pos=result.geometry.getAttribute('position'),ringCoords=[];for(let r=0;r<result.ringsCount;r++)for(let i=0;i<result.sectionCount;i++){const a=(r*result.sectionCount+i)*3,b=(r*result.sectionCount+(i+1)%result.sectionCount)*3;ringCoords.push(pos.array[a],pos.array[a+1],pos.array[a+2],pos.array[b],pos.array[b+1],pos.array[b+2]);}const rg=new THREE.BufferGeometry();rg.setAttribute('position',new THREE.Float32BufferAttribute(ringCoords,3));ringLines=new THREE.LineSegments(rg,new THREE.LineBasicMaterial({color:0xf1d27a,transparent:true,opacity:.64}));ringLines.visible=$('ringsBtn').classList.contains('active');scene.add(ringLines);
  const pg=new THREE.BufferGeometry().setFromPoints(result.points.concat(result.closed?[result.points[0]]:[]));pathLine=new THREE.Line(pg,new THREE.LineBasicMaterial({color:0x74b9ff}));pathLine.visible=$('pathBtn').classList.contains('active');scene.add(pathLine);
  edgeOverlay=new THREE.LineSegments(new THREE.WireframeGeometry(displayGeometry),new THREE.LineBasicMaterial({color:0x7fe8ff,transparent:true,opacity:.68}));edgeOverlay.visible=$('edgesBtn').classList.contains('active');scene.add(edgeOverlay);
  boundaryOverlay=new THREE.LineSegments(boundaryGeometry(displayGeometry),new THREE.LineBasicMaterial({color:0xff4d61,linewidth:2}));boundaryOverlay.visible=$('boundaryBtn').classList.contains('active');scene.add(boundaryOverlay);
  const collisionFaces=[],collisionPosition=result.geometry.getAttribute('position');(collisionDetection?.intersectingTriangles||[]).forEach(triangle=>triangle.forEach(index=>collisionFaces.push(collisionPosition.getX(index),collisionPosition.getY(index),collisionPosition.getZ(index))));const collisionGeometry=new THREE.BufferGeometry();collisionGeometry.setAttribute('position',new THREE.Float32BufferAttribute(collisionFaces,3));collisionOverlay=new THREE.Mesh(collisionGeometry,new THREE.MeshBasicMaterial({color:0xffbf63,transparent:true,opacity:.7,side:THREE.DoubleSide,depthWrite:false}));collisionOverlay.visible=$('collisionBtn').classList.contains('active');scene.add(collisionOverlay);
  const dotGeometry=new THREE.BufferGeometry();dotGeometry.setAttribute('position',new THREE.Float32BufferAttribute(pos.array,3));vertexPoints=new THREE.Points(dotGeometry,new THREE.PointsMaterial({color:0xff8f70,size:.055,sizeAttenuation:true}));vertexPoints.visible=state.vertices;scene.add(vertexPoints);
  if(state.bbox){boxHelper=new THREE.BoxHelper(surface,0x9be28f);scene.add(boxHelper);}
  if(displayGeometry!==result.geometry)result.geometry.dispose();const box=new THREE.Box3().setFromObject(surface), size=box.getSize(new THREE.Vector3()),displayPositions=displayGeometry.getAttribute('position'),displayTriangles=displayGeometry.index?displayGeometry.index.count/3:displayPositions.count/3,warning=result.tightBends?` · ${result.tightBends} tight bend${result.tightBends===1?'':'s'}`:'',mergeState=booleanQueued?' · Boolean check queued':booleanMerged?` · crisp Boolean union (${booleanOperands} solids)`:booleanChecked?' · no separated overlaps':state.collisionMode==='merge'?(manifoldError?` · Boolean unavailable: ${manifoldError}`:' · loading Boolean engine…'):'';$('meshMeta').textContent=`${result.ringsCount} rings · ${result.sectionCount} section points · ${Math.round(displayTriangles).toLocaleString()} triangles${mergeState}${warning}`;$('meshStats').innerHTML=`<div class="metric"><strong>${displayPositions.count.toLocaleString()}</strong><span>vertices</span></div><div class="metric"><strong>${Math.round(displayTriangles).toLocaleString()}</strong><span>triangles</span></div><div class="metric"><strong>${result.ringsCount}</strong><span>cross-sections</span></div><div class="metric"><strong>${size.x.toFixed(1)} × ${size.y.toFixed(1)} × ${size.z.toFixed(1)}</strong><span>bounds</span></div>`;$('formTitle').textContent=$('modeInput').selectedOptions[0].text;persist();
}
function fit(){if(!surface)return;const box=new THREE.Box3().setFromObject(surface),center=box.getCenter(new THREE.Vector3()),radius=Math.max(.1,box.getSize(new THREE.Vector3()).length()/2);controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(radius*1.45,radius*1.1,radius*1.75));camera.near=radius/100;camera.far=radius*100;camera.updateProjectionMatrix();controls.update();}
function outputValues(){[['length',1],['endScale',2],['twist',0],['radius',1],['turns',2],['opacity',2],['clearance',2]].forEach(([k,d])=>{$(k+'Value').textContent=k==='twist'?`${state[k]}°`:state[k].toFixed(d);});}
function populateControls(){ensureStations();for(const [key,value]of Object.entries(state)){const input=$(key+'Input');if(input)input.value=value;}$('endScaleNumber').value=state.endScale;$('startScaleInput').value=state.startScale;$('modeInput').value=state.mode;$('collisionModeInput').value=state.collisionMode;$('recomputeBooleanBtn').disabled=state.collisionMode!=='merge';$('capStart').checked=state.capStart;$('capEnd').checked=state.capEnd;$('smoothInput').checked=state.smooth;$('resampleInput').checked=state.resample;$('bboxInput').checked=state.bbox;$('verticesInput').checked=state.vertices;$('pathSmoothInput').checked=state.pathSmooth;$('modulationInput').value=state.modulation;outputValues();renderStations();}
function readControls(){['segments','samples','length','endScale','twist','radius','turns','opacity','startScale','amplitude','frequency','clearance'].forEach(key=>{const input=$(key+'Input');if(input)state[key]=Number(input.value);});state.capStart=$('capStart').checked;state.capEnd=$('capEnd').checked;state.smooth=$('smoothInput').checked;state.resample=$('resampleInput').checked;state.bbox=$('bboxInput').checked;state.vertices=$('verticesInput').checked;state.modulation=$('modulationInput').value;state.collisionMode=$('collisionModeInput').value;state.mode=$('modeInput').value;outputValues();}
const stationControlIds=new Set(['stationPositionInput','stationScaleInput','stationRotationInput','stationOffsetXInput','stationOffsetYInput']);
const rebuildControlIds=new Set(['segmentsInput','samplesInput','lengthInput','startScaleInput','endScaleInput','endScaleNumber','twistInput','radiusInput','turnsInput','modulationInput','amplitudeInput','frequencyInput','collisionModeInput','clearanceInput','capStart','capEnd','smoothInput','resampleInput','bboxInput','verticesInput','opacityInput','modeInput']);
function applyGeneralControl(input){if(input.id==='endScaleNumber')$('endScaleInput').value=input.value;if(input.id==='endScaleInput')$('endScaleNumber').value=input.value;readControls();rebuild(true);}
document.querySelectorAll('input,select').forEach(input=>{
  if(stationControlIds.has(input.id)||!rebuildControlIds.has(input.id))return;
  if(input.type==='number'){
    input.addEventListener('change',()=>{applyGeneralControl(input);checkpoint();});
    input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();input.blur();}});
  }else{
    input.addEventListener('input',()=>applyGeneralControl(input));
    input.addEventListener('change',checkpoint);
  }
});
function updateActiveStation(){const s=state.stations[activeStation];s.position=THREE.MathUtils.clamp(Number($('stationPositionInput').value),0,1);s.scale=Math.max(.01,Number($('stationScaleInput').value));s.rotation=Number($('stationRotationInput').value);s.offsetX=Number($('stationOffsetXInput').value);s.offsetY=Number($('stationOffsetYInput').value);state.stations.sort((a,b)=>a.position-b.position);activeStation=state.stations.indexOf(s);state.polygon=s.polygon;rebuild();}
['stationPositionInput','stationScaleInput','stationRotationInput','stationOffsetXInput','stationOffsetYInput'].forEach(id=>{
  const input=$(id);
  input.addEventListener('change',()=>{updateActiveStation();checkpoint();});
  input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();input.blur();}});
});
$('pathSmoothInput').addEventListener('change',()=>{state.pathSmooth=$('pathSmoothInput').checked;checkpoint();rebuild();});
$('recomputeBooleanBtn').onclick=()=>{if(state.collisionMode!=='merge')return;manifoldError='';rebuild();};
$('addStationBtn').onclick=()=>{const current=state.stations[activeStation],next=state.stations[activeStation+1],position=next?(current.position+next.position)/2:Math.min(.99,current.position+.1);state.stations.push(station(current.polygon,position,current.scale));activeStation=state.stations.length-1;ensureStations();checkpoint();populateControls();rebuild();};
$('duplicateStationBtn').onclick=()=>{const current=state.stations[activeStation],copy=station(current.polygon,Math.min(.99,current.position+.04),current.scale);copy.rotation=current.rotation;copy.offsetX=current.offsetX;copy.offsetY=current.offsetY;state.stations.push(copy);activeStation=state.stations.length-1;ensureStations();checkpoint();populateControls();rebuild();};
$('removeStationBtn').onclick=()=>{if(state.stations.length<=2)return;state.stations.splice(activeStation,1);activeStation=Math.max(0,activeStation-1);ensureStations();checkpoint();populateControls();rebuild();};
function setPreset(name){const presets={prism:{mode:'straight',startScale:1,endScale:1,twist:0,modulation:'constant'},horn:{mode:'arc',startScale:1,endScale:.32,twist:40,radius:4,turns:.55},twist:{mode:'straight',startScale:1,endScale:.7,twist:180},arc:{mode:'arc',startScale:1,endScale:.7,twist:90,radius:3,turns:.7},helix:{mode:'straight',startScale:1,endScale:.6,twist:110,radius:3,turns:1.25},ring:{mode:'ring',startScale:1,endScale:1,twist:0,radius:4,turns:1},ribbed:{mode:'straight',startScale:1,endScale:1,twist:0,modulation:'sine',amplitude:.16,frequency:8},relic:{mode:'straight',startScale:1,endScale:.52,twist:90,segments:10,smooth:false,modulation:'stepped',frequency:5}};Object.assign(state,presets[name]);populateControls();checkpoint();rebuild();fit();document.querySelectorAll('.mode-tab').forEach(b=>b.classList.toggle('active',b.dataset.preset===name));}
document.querySelectorAll('[data-preset]').forEach(button=>button.addEventListener('click',()=>setPreset(button.dataset.preset)));
$('undoBtn').onclick=()=>{if(historyIndex>0){historyIndex--;restore(history[historyIndex]);updateUndoButtons();}};$('redoBtn').onclick=()=>{if(historyIndex<history.length-1){historyIndex++;restore(history[historyIndex]);updateUndoButtons();}};$('resetBtn').onclick=()=>{state=clone(DEFAULTS);populateControls();checkpoint();rebuild();fit();};$('fitBtn').onclick=fit;
$('wireBtn').onclick=()=>{if(surface){surface.material.wireframe=!surface.material.wireframe;$('wireBtn').classList.toggle('active',surface.material.wireframe);}};$('edgesBtn').onclick=()=>{$('edgesBtn').classList.toggle('active');if(edgeOverlay)edgeOverlay.visible=$('edgesBtn').classList.contains('active');};$('boundaryBtn').onclick=()=>{$('boundaryBtn').classList.toggle('active');if(boundaryOverlay)boundaryOverlay.visible=$('boundaryBtn').classList.contains('active');};$('collisionBtn').onclick=()=>{$('collisionBtn').classList.toggle('active');if(collisionOverlay)collisionOverlay.visible=$('collisionBtn').classList.contains('active');};$('ringsBtn').onclick=()=>{$('ringsBtn').classList.toggle('active');if(ringLines)ringLines.visible=$('ringsBtn').classList.contains('active');};$('pathBtn').onclick=()=>{$('pathBtn').classList.toggle('active');if(pathLine)pathLine.visible=$('pathBtn').classList.contains('active');};$('axesBtn').onclick=()=>{$('axesBtn').classList.toggle('active');axes.visible=grid.visible=$('axesBtn').classList.contains('active');};
$('clearBtn').onclick=()=>{state.stations[activeStation].polygon=[];state.polygon=state.stations[activeStation].polygon;checkpoint();rebuild();};$('closeBtn').onclick=()=>{dragging=false;renderEditor();};$('recenterBtn').onclick=()=>{const c=polygonCentroid();state.stations[activeStation].polygon=state.polygon.map(p=>[p[0]-c[0],p[1]-c[1]]);state.polygon=state.stations[activeStation].polygon;checkpoint();rebuild();};
document.addEventListener('keydown',event=>{const tag=document.activeElement?.tagName;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?$('redoBtn').click():$('undoBtn').click();return;}if(tag==='INPUT'||tag==='SELECT')return;if((event.key==='Delete'||event.key==='Backspace')&&pathSelected!==null&&state.pathPoints.length>2){state.pathPoints.splice(pathSelected,1);pathSelected=null;checkpoint();rebuild();return;}if((event.key==='Delete'||event.key==='Backspace')&&selected!==null&&state.polygon.length>3){state.polygon.splice(selected,1);selected=null;checkpoint();rebuild();}if(event.key.toLowerCase()==='f')fit();if(event.key.toLowerCase()==='w')$('wireBtn').click();});
function download(filename,text,type){const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([text],{type}));link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),0);}
function safeName(){return ($('filenameInput').value.trim()||'irregular-sweep').replace(/[^a-z0-9._-]+/gi,'-');}
$('objBtn').onclick=()=>{if(!surface)return;surface.updateMatrixWorld(true);const p=surface.geometry.getAttribute('position'),index=surface.geometry.index,array=index?index.array:Array.from({length:p.count},(_,i)=>i),v=new THREE.Vector3();let out='# Irregular Polygon Sweep\n';for(let i=0;i<p.count;i++){v.fromBufferAttribute(p,i).applyMatrix4(surface.matrixWorld);out+=`v ${v.x} ${v.y} ${v.z}\n`;}for(let i=0;i<array.length;i+=3)out+=`f ${array[i]+1} ${array[i+1]+1} ${array[i+2]+1}\n`;download(`${safeName()}.obj`,out,'text/plain');};
$('stlBtn').onclick=()=>{if(!surface)return;surface.updateMatrixWorld(true);const g=surface.geometry,p=g.getAttribute('position'),idx=g.index?g.index.array:Array.from({length:p.count},(_,i)=>i);let out='solid irregular_polygon_sweep\n';const a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3(),normal=new THREE.Vector3();for(let i=0;i<idx.length;i+=3){a.fromBufferAttribute(p,idx[i]).applyMatrix4(surface.matrixWorld);b.fromBufferAttribute(p,idx[i+1]).applyMatrix4(surface.matrixWorld);c.fromBufferAttribute(p,idx[i+2]).applyMatrix4(surface.matrixWorld);normal.copy(b).sub(a).cross(c.clone().sub(a)).normalize();out+=` facet normal ${normal.x} ${normal.y} ${normal.z}\n  outer loop\n   vertex ${a.x} ${a.y} ${a.z}\n   vertex ${b.x} ${b.y} ${b.z}\n   vertex ${c.x} ${c.y} ${c.z}\n  endloop\n endfacet\n`;}download(`${safeName()}.stl`,out+'endsolid irregular_polygon_sweep\n','text/plain');};
$('saveBtn').onclick=()=>download(`${safeName()}.json`,JSON.stringify({version:2,...state},null,2),'application/json');$('loadInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{state={...clone(DEFAULTS),...JSON.parse(reader.result)};populateControls();checkpoint();rebuild();fit();}catch{alert('This is not a readable Polygon Sweep project file.');}};reader.readAsText(file);};
new ResizeObserver(()=>{const r=viewport.getBoundingClientRect();camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false);}).observe(viewport);
function frame(){requestAnimationFrame(frame);controls.update();renderer.render(scene,camera);} frame();
populateControls();checkpoint();rebuild();fit();
