const MIN_SIZE=12,MAX_SIZE=64,MAX_STATE=3;
let SIZE=16;
const STORAGE_KEY='hrifa-grid-traversal-v1';
const $=id=>document.getElementById(id);
let board=Array.from({length:SIZE*SIZE},()=>({state:0,occupants:[],history:[]}));
let pieces=[],instances=[],selectedPieceId=null,selectedCell=0,round=0,runTimer=null,nextPieceId=1,nextInstanceId=1,editingPieceId=null,pendingPlacement=null,pieceMenuId=null,pendingPieceAction=null;
const transitionCost=(from,to)=>{let cost=0;for(let s=from;s<to;s++)cost+=[0,1,2][s]||0;return cost};
const createBoard=size=>Array.from({length:size*size},()=>({state:0,occupants:[],history:[]}));
const validSize=value=>[12,16,20,24,32,64].includes(+value)?+value:16;
const variableConfigFromEditor=()=>({nStart:Math.max(1,+$('nStart').value||1),nChange:Number.isFinite(+$('nChange').value)?+$('nChange').value:1,nEvery:Math.max(1,+$('nEvery').value||1)});
const normalizedVariableConfig=config=>({nStart:Math.max(1,+config?.nStart||1),nChange:Number.isFinite(+config?.nChange)?+config.nChange:1,nEvery:Math.max(1,+config?.nEvery||1)});
function parseMove(text){const cores=[],matcher=/\[\s*([FBLR])\s*,?\s*(\d+|n)\s*\.\s*([ox+\-])(?:\s*,?\s*(\d+))?\s*\]|([<>])/gi;let found='',m;while((m=matcher.exec(text))){found+=m[0];if(m[5]){cores.push({kind:'turn',turn:m[5]==='>'?'R':'L'});continue}const action=m[3],intensity=m[4]===undefined?(action==='o'?0:NaN):+m[4];if(!Number.isInteger(intensity)||intensity<0)return{error:`${m[0]} needs a non-negative intensity.`};cores.push({kind:'move',direction:m[1].toUpperCase(),distance:m[2].toLowerCase()==='n'?'n':+m[2],action,intensity});}if(!cores.some(core=>core.kind==='move'))return{error:'Include at least one movement core, such as [F,2.x,2].'};if(found.replace(/\s/g,'')!==text.replace(/\s/g,''))return{error:'Use movement cores plus optional > or < turns; distance can be a number or n.'};return{cores,normal:cores.map(c=>c.kind==='turn'?(c.turn==='R'?'>':'<'):`[${c.direction},${c.distance}.${c.action},${c.intensity}]`).join('')}}
function updateParse(){const result=parseMove($('pieceMove').value);const out=$('parseReadout');out.classList.toggle('error',!!result.error);out.textContent=result.error||`${result.normal}\n${result.cores.map(c=>c.kind==='turn'?describeCore(c):`move ${c.direction} ${c.distance}: ${describeCore(c)}`).join(' then ')}`;return result}
function describeCore(c){if(c.kind==='turn')return c.turn==='R'?'turn clockwise':'turn counter-clockwise';return c.action==='o'?'no state change':c.action==='x'?`paint up to ${c.intensity}`:c.action==='+'?`raise by ${c.intensity}`:`lower by ${c.intensity}`}
function facingVector(facing,direction){const dirs=['N','E','S','W'],base=dirs.indexOf(facing),relative={F:0,R:1,B:2,L:3}[direction],out=dirs[(base+relative)%4];return{N:[0,-1],E:[1,0],S:[0,1],W:[-1,0]}[out]}
function rotateFacing(facing,turn){const dirs=['N','E','S','W'],shift=turn==='R'?1:3;return dirs[(dirs.indexOf(facing)+shift)%4]}
function newPiece(){editingPieceId=null;$('pieceName').value='';$('pieceTokens').value=4;$('pieceEnergy').value=18;$('pieceMove').value='[F,2.x,1][R,1.o]';const config={nStart:1,nChange:1,nEvery:2};$('nStart').value=config.nStart;$('nChange').value=config.nChange;$('nEvery').value=config.nEvery;$('savePieceButton').textContent='Add piece';updateParse()}
function savePiece(asNew=false){const parsed=updateParse();if(parsed.error)return;const name=$('pieceName').value.trim()||'Untitled piece',tokens=Math.max(1,+$('pieceTokens').value||1),energy=Math.max(0,+$('pieceEnergy').value||0),variableConfig=variableConfigFromEditor();const data={id:(!asNew&&editingPieceId)||nextPieceId++,name,tokens,energy,moveText:parsed.normal,cores:parsed.cores,variableConfig};if(!asNew&&editingPieceId){const index=pieces.findIndex(p=>p.id===editingPieceId);pieces[index]=data;instances.filter(i=>i.pieceId===data.id).forEach(i=>Object.assign(i,{energy,cores:data.cores,name:data.name,variableConfig:data.variableConfig,startVariables:{n:data.variableConfig.nStart}}));log(`Updated ${data.name}.`)}else{pieces.push(data);log(`Added ${data.name} to the stable.`)}selectedPieceId=data.id;editingPieceId=data.id;$('savePieceButton').textContent='Update piece';render();}
function editPiece(id){const p=pieces.find(piece=>piece.id===id);if(!p)return;const config=normalizedVariableConfig(p.variableConfig);editingPieceId=id;$('pieceName').value=p.name;$('pieceTokens').value=p.tokens;$('pieceEnergy').value=p.energy;$('pieceMove').value=p.moveText;$('nStart').value=config.nStart;$('nChange').value=config.nChange;$('nEvery').value=config.nEvery;$('savePieceButton').textContent='Update piece';updateParse();}
function placementsFor(pieceId){return instances.filter(i=>i.pieceId===pieceId).length}
function requestPlacement(cellIndex){const piece=pieces.find(p=>p.id===selectedPieceId);if(!piece)return;if(placementsFor(piece.id)>=piece.tokens){log(`${piece.name} has already placed all ${piece.tokens} tokens.`);return}selectedCell=cellIndex;pendingPlacement={pieceId:piece.id,cell:cellIndex};render()}
function placeToken(facing){if(!pendingPlacement)return;const {pieceId,cell:cellIndex}=pendingPlacement,piece=pieces.find(p=>p.id===pieceId);if(!piece)return;const variableConfig=normalizedVariableConfig(piece.variableConfig),variables={n:variableConfig.nStart},startVariables={...variables};const inst={id:nextInstanceId++,pieceId:piece.id,name:piece.name,energy:piece.energy,facing,cores:piece.cores,variableConfig,variables,startVariables,variableMoves:0,cell:cellIndex,startCell:cellIndex,startFacing:facing,startEnergy:piece.energy,coreIndex:0,stepInCore:0,status:'active',last:'Placed'};instances.push(inst);board[cellIndex].occupants.push(inst.id);board[cellIndex].history.push(`Placed ${piece.name}, facing ${facing}`);selectedCell=cellIndex;pendingPlacement=null;log(`${piece.name} token ${placementsFor(piece.id)} placed at ${coord(cellIndex)}, facing ${facing}.`);render()}
function actionFor(core,old){if(core.action==='o')return{next:old,cost:0,changed:false};if(core.action==='x'){const next=old<core.intensity?Math.min(core.intensity,MAX_STATE):old;return{next,cost:transitionCost(old,next),changed:next!==old}}if(core.action==='+'){const next=Math.min(MAX_STATE,old+core.intensity);return{next,cost:transitionCost(old,next),changed:next!==old}}const next=Math.max(0,old-core.intensity);return{next,cost:0,changed:next!==old}}
function attemptStep(inst){if(inst.status!=='active')return;const turns=[];while(inst.cores[inst.coreIndex].kind==='turn'){const turn=inst.cores[inst.coreIndex];inst.facing=rotateFacing(inst.facing,turn.turn);turns.push(turn.turn==='R'?'clockwise':'counter-clockwise');inst.coreIndex=(inst.coreIndex+1)%inst.cores.length}const core=inst.cores[inst.coreIndex],distance=core.distance==='n'?inst.variables.n:core.distance;const [dx,dy]=facingVector(inst.facing,core.direction),[x,y]=coord(inst.cell),nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=SIZE||ny>=SIZE){inst.status='Imp';inst.last=`${turns.length?'Turned '+turns.join(', ')+'; ':''}next step leaves the board`;return}const target=ny*SIZE+nx,cell=board[target],change=actionFor(core,cell.state),cost=(+$('moveCost').value||0)+change.cost+(+$('occupancyCost').value||0)*cell.occupants.length;if(inst.energy<=0){inst.status='Ex';inst.last='No energy before next step';return}if(cost>inst.energy){inst.status=(inst.coreIndex>0||inst.stepInCore>0)?'Int':'Un';inst.last=`Need ${cost}, have ${inst.energy}`;return}board[inst.cell].occupants=board[inst.cell].occupants.filter(id=>id!==inst.id);cell.occupants.push(inst.id);inst.cell=target;inst.energy-=cost;if(change.changed){cell.history.push(`${inst.name}: ${cell.state} -> ${change.next}`);cell.state=change.next}inst.stepInCore++;if(inst.stepInCore>=distance){inst.stepInCore=0;inst.coreIndex=(inst.coreIndex+1)%inst.cores.length;inst.variableMoves++;if(inst.variableMoves>=inst.variableConfig.nEvery){inst.variables.n=Math.max(1,inst.variables.n+inst.variableConfig.nChange);inst.variableMoves=0}}inst.last=`${turns.length?'Turned '+turns.join(', ')+'; ':''}entered ${coord(target)}; cost ${cost}${change.changed?`; state -> ${cell.state}`:''}`}
function advanceRound(){if(!instances.some(i=>i.status==='active'))return false;const activeIds=new Set(instances.filter(i=>i.status==='active').map(i=>i.id));round++;instances.slice().sort((a,b)=>a.id-b.id).forEach(attemptStep);instances.filter(i=>activeIds.has(i.id)&&i.status!=='active').forEach(i=>log(`${i.name} #${i.id}: ${i.status} (${i.last}).`));return true}
function stepRound(){if(!advanceRound()){stopRun();log('All placed pieces are resting.');render();return}render()}
function resolveAll(){stopRun();const limit=50000;let completed=0;while(completed<limit&&advanceRound())completed++;if(instances.some(i=>i.status==='active'))log(`Resolve paused after ${limit.toLocaleString()} rounds: an active rule may be a zero-cost loop.`);else log(`Resolved ${completed} round${completed===1?'':'s'} to the final resting field.`);render()}
function toggleRun(){if(runTimer){stopRun();return}$('runButton').textContent='Pause';runTimer=setInterval(()=>{stepRound();if(!instances.some(i=>i.status==='active'))stopRun()},220)}function stopRun(){if(runTimer)clearInterval(runTimer);runTimer=null;$('runButton').textContent='Run'}
function rebuildOccupancy(){board.forEach(cell=>cell.occupants=[]);instances.forEach(instance=>board[instance.cell]?.occupants.push(instance.id))}
function resizeGrid(){const nextSize=validSize($('gridSize').value),oldSize=SIZE;if(nextSize===oldSize)return;stopRun();const oldBoard=board,convert=index=>{const x=index%oldSize,y=Math.floor(index/oldSize);return x<nextSize&&y<nextSize?y*nextSize+x:null};SIZE=nextSize;board=createBoard(SIZE);for(let y=0;y<Math.min(oldSize,SIZE);y++)for(let x=0;x<Math.min(oldSize,SIZE);x++){const oldCell=oldBoard[y*oldSize+x],cell=board[y*SIZE+x];cell.state=oldCell.state;cell.history=oldCell.history}const before=instances.length;instances=instances.filter(instance=>{const cell=convert(instance.cell),startCell=convert(instance.startCell);if(cell===null||startCell===null)return false;instance.cell=cell;instance.startCell=startCell;return true});selectedCell=convert(selectedCell)??0;pendingPlacement=null;pieceMenuId=null;pendingPieceAction=null;rebuildOccupancy();log(`Grid resized to ${SIZE} × ${SIZE}${before!==instances.length?`; removed ${before-instances.length} token(s) outside the new field`:''}.`);render()}
function resetPieces(){stopRun();pendingPlacement=null;pieceMenuId=null;pendingPieceAction=null;instances.forEach(instance=>{instance.cell=instance.startCell;instance.facing=instance.startFacing;instance.energy=instance.startEnergy;instance.variables={...instance.startVariables};instance.variableMoves=0;instance.coreIndex=0;instance.stepInCore=0;instance.status='active';instance.last='Reset to starting placement'});board.forEach(c=>{c.state=0;c.history=[]});rebuildOccupancy();round=0;log('Pieces reset to their starting placements and grid values reset to state 0.');render()}
function resetGrid(){stopRun();pendingPlacement=null;pieceMenuId=null;pendingPieceAction=null;instances=[];board.forEach(c=>{c.state=0;c.occupants=[];c.history=[]});round=0;log('Grid reset: placements removed and cell values restored to state 0. Piece definitions are retained.');render()}
function deleteSelectedPiece(){const piece=pieces.find(p=>p.id===selectedPieceId);if(!piece)return;const removedIds=new Set(instances.filter(i=>i.pieceId===piece.id).map(i=>i.id));instances=instances.filter(i=>i.pieceId!==piece.id);board.forEach(cell=>{cell.occupants=cell.occupants.filter(id=>!removedIds.has(id));cell.history.push(`Removed ${piece.name}`)});pieces=pieces.filter(p=>p.id!==piece.id);selectedPieceId=pieces[0]?.id||null;pendingPlacement=null;log(`Deleted ${piece.name} and removed its ${removedIds.size} placed token(s).`);if(selectedPieceId)editPiece(selectedPieceId);else newPiece();render()}
function renamePiece(pieceId,name){const piece=pieces.find(item=>item.id===pieceId),next=name.trim();if(!piece)return;if(next&&next!==piece.name){piece.name=next;instances.filter(instance=>instance.pieceId===pieceId).forEach(instance=>instance.name=next);log(`Renamed stable piece to ${next}.`)}render()}
function coord(index){return[index%SIZE,Math.floor(index/SIZE)]}
function moveInstance(instanceId,target){const instance=instances.find(item=>item.id===instanceId);if(!instance)return;board[instance.cell].occupants=board[instance.cell].occupants.filter(id=>id!==instance.id);instance.cell=target;board[target].occupants.push(instance.id);instance.last=`Manually moved to ${coord(target)}`;pendingPieceAction=null;log(`${instance.name} #${instance.id} manually moved to ${coord(target)}.`);render()}
function reorientInstance(instanceId,facing){const instance=instances.find(item=>item.id===instanceId);if(!instance)return;instance.facing=facing;instance.last=`Manually reoriented to ${facing}`;pendingPieceAction=null;log(`${instance.name} #${instance.id} reoriented to ${facing}.`);render()}
function removeInstance(instanceId){const instance=instances.find(item=>item.id===instanceId);if(!instance)return;board[instance.cell].occupants=board[instance.cell].occupants.filter(id=>id!==instance.id);instances=instances.filter(item=>item.id!==instanceId);pieceMenuId=null;pendingPieceAction=null;log(`Removed ${instance.name} #${instance.id}.`);render()}
function selectCell(index){selectedCell=index;if(pendingPieceAction?.type==='move'){moveInstance(pendingPieceAction.instanceId,index);return}const value=$('stateEditor').value;if(value==='place')requestPlacement(index);else{pendingPlacement=null;pieceMenuId=null;board[index].state=+value;board[index].history.push(`Initial state set to ${value}`);render()}}
function addOrientationPicker(el,cellIndex){const reorienting=pendingPieceAction?.type==='reorient',chooser=document.createElement('span');chooser.className='orientation-picker';[['N','↑'],['E','→'],['S','↓'],['W','←']].forEach(([facing,label])=>{const choice=document.createElement('span');choice.className=`orientation-choice ${facing.toLowerCase()}`;choice.textContent=label;choice.title=`Choose facing ${facing}`;choice.addEventListener('click',event=>{event.stopPropagation();reorienting?reorientInstance(pendingPieceAction.instanceId,facing):placeToken(facing)});chooser.append(choice)});el.append(chooser)}
function addPieceMenu(el,instance){const menu=document.createElement('span');menu.className='piece-action-picker';[['move','M','Move this token'],['reorient','↻','Reorient this token'],['remove','×','Remove this token']].forEach(([action,label,title])=>{const choice=document.createElement('span');choice.className=`piece-action ${action}`;choice.textContent=label;choice.title=title;choice.addEventListener('click',event=>{event.stopPropagation();pieceMenuId=null;if(action==='remove')removeInstance(instance.id);else{pendingPieceAction={type:action,instanceId:instance.id};render()}});menu.append(choice)});el.append(menu)}
function renderBoard(){const root=$('board');root.style.gridTemplateColumns=`repeat(${SIZE},1fr)`;root.dataset.size=SIZE;root.setAttribute('aria-label',`${SIZE} by ${SIZE} traversal board`);root.innerHTML='';board.forEach((cell,index)=>{const el=document.createElement('button');el.className='cell';el.dataset.state=cell.state;el.title=`${coord(index)} / state ${cell.state} / ${cell.occupants.length} occupant(s)`;el.addEventListener('click',()=>selectCell(index));cell.occupants.forEach((id,order)=>{const inst=instances.find(i=>i.id===id),tag=document.createElement('span');tag.className=`token ${inst.status==='active'?'active':'rest'}`;tag.style.left=`${3+(order%3)*31}%`;tag.style.top=`${3+Math.floor(order/3)*32}%`;tag.textContent=inst.status==='active'?`${arrow(inst.facing)}${inst.energy}`:inst.status;tag.title=`${inst.name} #${inst.id}: ${inst.status==='active'?inst.energy+' energy; ':''}click for options`;tag.addEventListener('click',event=>{event.stopPropagation();pieceMenuId=inst.id;pendingPlacement=null;pendingPieceAction=null;render()});el.append(tag);if(pieceMenuId===inst.id)addPieceMenu(el,inst)});if(pendingPlacement?.cell===index||pendingPieceAction?.type==='reorient'&&instances.find(item=>item.id===pendingPieceAction.instanceId)?.cell===index)addOrientationPicker(el,index);root.append(el)})}
function arrow(f){return{N:'↑',E:'→',S:'↓',W:'←'}[f]}
function renderPieces(){const root=$('pieceList');root.innerHTML='';pieces.forEach(p=>{const placed=placementsFor(p.id),card=document.createElement('div'),title=document.createElement('strong');card.className=`piece-card ${p.id===selectedPieceId?'selected':''}`;title.className='piece-name';title.textContent=p.name;title.title='Double-click to rename';title.addEventListener('click',event=>event.stopPropagation());title.addEventListener('dblclick',event=>{event.stopPropagation();const input=document.createElement('span');input.className='piece-rename';input.contentEditable='true';input.setAttribute('role','textbox');input.setAttribute('aria-label','Rename piece');input.textContent=p.name;const commit=()=>renamePiece(p.id,input.textContent);input.addEventListener('click',innerEvent=>innerEvent.stopPropagation());input.addEventListener('keydown',keyEvent=>{if(keyEvent.key==='Enter'){keyEvent.preventDefault();commit()}if(keyEvent.key==='Escape')render()});input.addEventListener('blur',commit,{once:true});title.replaceWith(input);input.focus();const selection=window.getSelection(),range=document.createRange();range.selectNodeContents(input);selection.removeAllRanges();selection.addRange(range)});card.append(title);const detail=document.createElement('small');detail.textContent=p.moveText;card.append(detail);const tokens=document.createElement('div');tokens.className='tokens';tokens.innerHTML=`<span>${placed} / ${p.tokens} placed</span><span>${p.energy} energy</span>`;card.append(tokens);card.addEventListener('click',()=>{selectedPieceId=p.id;editPiece(p.id);render()});root.append(card)});$('placementHint').textContent=pieces.length?'Click a piece to edit its rules; double-click its title to rename.':'Add a piece to begin.'}
function renderInspector(){const c=board[selectedCell],items=c.occupants.map(id=>instances.find(i=>i.id===id));$('inspector').innerHTML=`<dl><dt>Cell</dt><dd>(${coord(selectedCell).join(', ')})</dd><dt>State</dt><dd>${c.state}</dd><dt>Occupants</dt><dd>${items.length||'none'}</dd><dt>Pieces</dt><dd>${items.length?items.map(i=>`${i.name} #${i.id} (${i.status==='active'?i.energy+' energy':i.status}; n=${i.variables?.n??1})`).join('<br>'):'-'}</dd><dt>History</dt><dd>${c.history.slice(-4).join('<br>')||'-'}</dd></dl>`}
function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({gridSize:SIZE,pieces,instances,board:board.map(cell=>({state:cell.state,history:cell.history})),selectedPieceId,editingPieceId,selectedCell,round,nextPieceId,nextInstanceId,pendingPlacement,pendingPieceAction}))}catch(error){console.warn('Could not save Grid Traversal state.',error)}}
function restore(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)),savedSize=validSize(saved?.gridSize||Math.sqrt(saved?.board?.length||0));if(!saved||!Array.isArray(saved.board)||saved.board.length!==savedSize*savedSize)return false;SIZE=savedSize;board=createBoard(SIZE);pieces=Array.isArray(saved.pieces)?saved.pieces:[];pieces.forEach(piece=>piece.variableConfig=normalizedVariableConfig(piece.variableConfig));instances=Array.isArray(saved.instances)?saved.instances:[];board.forEach((cell,index)=>{const stored=saved.board[index]||{};cell.state=Number.isInteger(stored.state)&&stored.state>=0&&stored.state<=MAX_STATE?stored.state:0;cell.history=Array.isArray(stored.history)?stored.history:[];cell.occupants=[]});instances=instances.filter(instance=>Number.isInteger(instance.cell)&&instance.cell>=0&&instance.cell<board.length);instances.forEach(instance=>{const piece=pieces.find(item=>item.id===instance.pieceId),config=normalizedVariableConfig(instance.variableConfig||piece?.variableConfig);instance.variableConfig=config;instance.variables={n:Math.max(1,+instance.variables?.n||config.nStart)};instance.startVariables={n:Math.max(1,+instance.startVariables?.n||config.nStart)};instance.variableMoves=Math.max(0,+instance.variableMoves||0);instance.startCell=Number.isInteger(instance.startCell)?instance.startCell:instance.cell;instance.startFacing=instance.startFacing||instance.facing;instance.startEnergy=Number.isFinite(instance.startEnergy)?instance.startEnergy:instance.energy;board[instance.cell].occupants.push(instance.id)});selectedPieceId=pieces.some(piece=>piece.id===saved.selectedPieceId)?saved.selectedPieceId:(pieces[0]?.id||null);editingPieceId=pieces.some(piece=>piece.id===saved.editingPieceId)?saved.editingPieceId:selectedPieceId;selectedCell=Number.isInteger(saved.selectedCell)&&saved.selectedCell<board.length?saved.selectedCell:0;round=Number.isInteger(saved.round)?saved.round:0;nextPieceId=Number.isInteger(saved.nextPieceId)?saved.nextPieceId:Math.max(0,...pieces.map(piece=>piece.id||0))+1;nextInstanceId=Number.isInteger(saved.nextInstanceId)?saved.nextInstanceId:Math.max(0,...instances.map(instance=>instance.id||0))+1;pendingPlacement=saved.pendingPlacement&&pieces.some(piece=>piece.id===saved.pendingPlacement.pieceId)?saved.pendingPlacement:null;pendingPieceAction=saved.pendingPieceAction&&instances.some(instance=>instance.id===saved.pendingPieceAction.instanceId)?saved.pendingPieceAction:null;return true}catch(error){console.warn('Could not restore Grid Traversal state.',error);return false}}
function render(){renderBoard();renderPieces();renderInspector();$('roundReadout').textContent=`Round ${round}`;const p=pieces.find(x=>x.id===selectedPieceId);$('boardMode').textContent=$('stateEditor').value==='place'?(pendingPieceAction?.type==='move'?'Choose a destination cell for the selected token.':pendingPieceAction?.type==='reorient'?'Choose one of the four arrows to reorient the selected token.':pendingPlacement?`Choose one of the four arrows at ${coord(pendingPlacement.cell)} to set this token's forward orientation.`:p?`Placing ${p.name}: ${placementsFor(p.id)} / ${p.tokens}. Click a cell, then choose its arrow.`:'Select a piece to place tokens.'):`Editing cells: click to set state ${$('stateEditor').value}.`;persist()}
function log(message){const item=document.createElement('li');item.textContent=message;$('eventLog').prepend(item);while($('eventLog').children.length>35)$('eventLog').lastElementChild.remove()}
$('pieceMove').addEventListener('input',updateParse);$('newPieceButton').addEventListener('click',newPiece);$('savePieceButton').addEventListener('click',()=>savePiece());$('saveAsNewPieceButton').addEventListener('click',()=>savePiece(true));$('deletePieceButton').addEventListener('click',deleteSelectedPiece);$('stepButton').addEventListener('click',stepRound);$('runButton').addEventListener('click',toggleRun);$('resolveButton').addEventListener('click',resolveAll);$('resetPiecesButton').addEventListener('click',resetPieces);$('resetGridButton').addEventListener('click',resetGrid);$('gridSize').addEventListener('change',resizeGrid);$('stateEditor').addEventListener('change',render);restore();$('gridSize').value=SIZE;if(selectedPieceId)editPiece(selectedPieceId);else newPiece();updateParse();render();
